# Data for assert statement

DATA_FROM_2002_04_22 = [{"char_code": "AUD", "nominal": "1", "name": "Австралийский доллар", "value": "16.8573"},
                        {"char_code": "GBP", "nominal": "1", "name": "Фунт стерлингов Соединенного королевства",
                         "value": "45.1576"},
                        {"char_code": "BYR", "nominal": "1000", "name": "Белорусских рублей", "value": "17.9418"},
                        {"char_code": "DKK", "nominal": "10", "name": "Датских крон", "value": "37.3526"},
                        {"char_code": "USD", "nominal": "1", "name": "Доллар США", "value": "31.1711"},
                        {"char_code": "EUR", "nominal": "1", "name": "Евро", "value": "27.7828"},
                        {"char_code": "ISK", "nominal": "100", "name": "Исландских крон", "value": "32.1186"},
                        {"char_code": "KZT", "nominal": "100", "name": "Казахстанских тенге", "value": "20.3843"},
                        {"char_code": "CAD", "nominal": "1", "name": "Канадский доллар", "value": "19.7887"},
                        {"char_code": "NOK", "nominal": "10", "name": "Норвежских крон", "value": "36.3723"},
                        {"char_code": "XDR", "nominal": "1", "name": "СДР (специальные права заимствования)",
                         "value": "39.2254"},
                        {"char_code": "SGD", "nominal": "1", "name": "Сингапурский доллар", "value": "17.1251"},
                        {"char_code": "TRL", "nominal": "1000000", "name": "Турецких лир", "value": "23.8311"},
                        {"char_code": "UAH", "nominal": "10", "name": "Украинских гривен", "value": "58.3991"},
                        {"char_code": "SEK", "nominal": "10", "name": "Шведских крон", "value": "30.2312"},
                        {"char_code": "CHF", "nominal": "1", "name": "Швейцарский франк", "value": "18.9202"},
                        {"char_code": "JPY", "nominal": "100", "name": "Японских иен", "value": "23.9649"}]

CURRENCY_CODES = ["AED", "AMD", "AUD", "AZN", "BGN", "BRL", "BYN", "BYR", "CAD", "CHF", "CNY", "CZK", "DKK", "EGP",
                  "EUR", "GBP",
                  "GEL", "HKD", "HUF", "IDR", "INR", "ISK", "JPY", "KGS", "KRW", "KZT", "MDL", "NOK", "NZD", "PLN",
                  "QAR", "RON",
                  "RSD", "SEK", "SGD", "THB", "TJS", "TMT", "TRL", "TRY", "UAH", "USD", "UZS", "VND", "XDR", "ZAR"]

PAGINATION_SET = [
    {"date": "2023-04-26", "char_code": "AMD", "nominal": "100", "name": "Армянских драмов", "value": "21.1138"},
    {"date": "2023-04-26", "char_code": "BYN", "nominal": "1", "name": "Белорусский рубль", "value": "27.7598"},
    {"date": "2023-04-26", "char_code": "BGN", "nominal": "1", "name": "Болгарский лев", "value": "45.8738"},
    {"date": "2023-04-26", "char_code": "BRL", "nominal": "1", "name": "Бразильский реал", "value": "16.1191"},
    {"date": "2023-04-26", "char_code": "HUF", "nominal": "100", "name": "Венгерских форинтов", "value": "23.8939"},
    {"date": "2023-04-26", "char_code": "VND", "nominal": "10000", "name": "Вьетнамских донгов", "value": "34.4995"},
    {"date": "2023-04-26", "char_code": "HKD", "nominal": "1", "name": "Гонконгский доллар", "value": "10.4071"},
    {"date": "2023-04-26", "char_code": "GEL", "nominal": "1", "name": "Грузинский лари", "value": "32.5302"},
    {"date": "2023-04-26", "char_code": "DKK", "nominal": "1", "name": "Датская крона", "value": "12.0383"},
    {"date": "2023-04-26", "char_code": "AED", "nominal": "1", "name": "Дирхам ОАЭ", "value": "22.2062"},
    {"date": "2023-04-26", "char_code": "USD", "nominal": "1", "name": "Доллар США", "value": "81.5499"},
    {"date": "2023-04-26", "char_code": "EUR", "nominal": "1", "name": "Евро", "value": "90.0332"},
    {"date": "2023-04-26", "char_code": "EGP", "nominal": "10", "name": "Египетских фунтов", "value": "26.3971"},
    {"date": "2023-04-26", "char_code": "INR", "nominal": "100", "name": "Индийских рупий", "value": "99.3622"},
    {"date": "2023-04-26", "char_code": "IDR", "nominal": "10000", "name": "Индонезийских рупий", "value": "55.202"},
    {"date": "2023-04-26", "char_code": "KZT", "nominal": "100", "name": "Казахстанских тенге", "value": "17.8704"},
    {"date": "2023-04-26", "char_code": "CAD", "nominal": "1", "name": "Канадский доллар", "value": "60.22"},
    {"date": "2023-04-26", "char_code": "QAR", "nominal": "1", "name": "Катарский риал", "value": "22.4038"},
    {"date": "2023-04-26", "char_code": "KGS", "nominal": "100", "name": "Киргизских сомов", "value": "93.1786"},
    {"date": "2023-04-26", "char_code": "CNY", "nominal": "1", "name": "Китайский юань", "value": "11.7664"}]
